name: master
on: [push]

jobs:
  documentation:
    runs-on: ubuntu-latest
    container: python:3.11-buster
    name: Document python files with pdoc
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - run: pip3 install -r requirements.txt

      - run: pdoc src/*.py -o html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload generator folder
          path: "html"

  deploy:
    needs: documentation
    name: "Deploy to Github pages"
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
